### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Matmut7** [SocialGouv/secretariat#14]
- [ ] optimiser les requêtes GH avec des *webhooks*
- [ ] rendre GH obligatoire et synchroniser les teams 
- [ ] formulaire de modification d'un *user*
- [ ] supporter de nouveaux services
- [ ] vue qui résume toutes les anomalies
- [ ] déployer derrière `oauth2-proxy`

Non prioritaire :
- [ ] formulaire rempli en partie par le presta et confirmé par un *core*
